---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	researcher(researcher)
	tools(tools)
	analyst(analyst)
	reporter(reporter)
	human_review(human_review<hr/><small><em>__interrupt = before</em></small>)
	__end__([<p>__end__</p>]):::last
	__start__ --> researcher;
	analyst --> reporter;
	human_review -.-> analyst;
	human_review -.-> researcher;
	researcher -.-> analyst;
	researcher -.-> human_review;
	researcher -.-> tools;
	tools --> researcher;
	reporter --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
